### ISSUE TITLE
[Feature request] Open port checker

### ISSUE THREAD

**Issue by greggameplayer** [whoopsmonitor/whoopsmonitor#12]
It would be great to have checker to test open port like for example testing if the ssh is working

**Comment by danielrataj** [comment]
Hi, do you mean during installation?

Thank you.

**Comment by greggameplayer** [comment]
No, i mean in order to check if another container is alive or not

**Comment by danielrataj** [comment]
Now I get it. You mean the "check" itself. Thank you for the idea. I'll check it out.

**Comment by danielrataj** [comment]
I created this checker for it:
https://github.com/whoopsmonitor/whoopsmonitor-check-port-open
